### ISSUE TITLE
About the color-spill problem and Fig.2. in your paper

### ISSUE THREAD

**Issue by xymsh** [MarcoForte/FBA_Matting#3]
Hi, I have read your paper on arxiv. In your paper, the color-spill problem was proposed and an example was given in Fig.2. I tried to reproduce your result in Fig.2 using the same foreground in Composition-1k dataset. But the composite image is totally different from yours. Besides, I tried to use Closed-form method to estimate a new foreground, but got a different one. My new fg is black in the area where alpha equals to zero.  

So how did you composite the original foreground onto the background? And how did you re-estimate the new foreground? Can you please share your code?

Thanks!

**Comment by MarcoForte** [comment]
Hi the full foreground expansion effect can be achieved by setting `CONST_ALPHA_MARGIN = 0.00`.
Then reset the opaque foreground values, with `foreground[alpha==1] = image[alpha==1]` 



However note that we do not use the exact code from https://github.com/MarcoForte/closed-form-matting/blob/master/solve_foreground_background.py
Since it is rather slow. 
Instead we use a custom multi-level solver written in C. Which we may release in the future.

**Comment by xymsh** [comment]
Thanks! Hope we can get the code soon.

**Comment by bebory** [comment]
When solve new foreground, what you set as the 'image' to 'solve_foreground_background' function? 
old fg or a composed image, or others?
