### ISSUE TITLE
double concatenation of input image?

### ISSUE THREAD

**Issue by mhashas** [MarcoForte/FBA_Matting#49]
https://github.com/MarcoForte/FBA_Matting/blob/master/networks/models.py#L208, here conv_out[-6] is conv_out[0], which is https://github.com/MarcoForte/FBA_Matting/blob/master/networks/models.py#L99 the actual image, so we're concatenating the image twice basically

am i correct or am i missing something?

**Comment by 99991** [comment]
One of the images is centered and  normalized by ImageNet standard deviation and mean while the other image is in original [0, 1] RGB space. Since the encoder network has been pretrained on standardized images, the input image should be standardized, but it is not necessary for the decoder.

Not sure if image standardization actually makes a difference or if it is just cargo cult, but we are stuck with it now. My guess is that you could use any of those two images and it would work almost the same.

https://github.com/MarcoForte/FBA_Matting/blob/8736764197f7768f1bd5e7d7797c9addf03c9917/demo.py#L74

![comparison](https://user-images.githubusercontent.com/18725165/152150417-db45bc54-a5f0-420f-9ca9-a0a1dea141ab.png)

**Comment by mhashas** [comment]
Thanks a lot for the clear response!
